# Part2： Numpy 中的索引 & 切片（筛选）

我们将讨论如何从数组中选择元素或元素组。

### 一、中括号 Bracket Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[0:2] # 左闭右开

array([0, 1])

In [4]:
arr[-2:] # 从倒数第二个数据开始到最后

array([ 9, 10])

In [5]:
# 对二维数组也是同理
tang_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
# 取第二行数据：
tang_arr[1]

array([4, 5, 6])

In [7]:
# 取第二列数据：
tang_arr[:,1]

array([2, 5, 8])

### 二、广播 Broadcasting

Numpy 数组不同于普通的 Python 列表，它们能够广播：

In [21]:
arr[0:5]=100 
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [22]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [24]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr #注意更改也发生在原始数组中！

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy = arr.copy() #arr_copy = arr.copy() a
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy[0] = 100
arr_copy

array([100,  99,  99,  99,  99,  99,   6,   7,   8,   9,  10])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

- 再举个例子

In [29]:
# 用0填充：
tang_arr.fill(0)
tang_arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
tang_arr3 = tang_arr # 这里两个数组是一样的
tang_arr3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
tang_arr3[1,1] = 100
tang_arr3

array([[  0,   0,   0],
       [  0, 100,   0],
       [  0,   0,   0]])

In [32]:
tang_arr

array([[  0,   0,   0],
       [  0, 100,   0],
       [  0,   0,   0]])

### 三、索引二维数组（矩阵）

In [34]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[2] # 第三行

array([35, 40, 45])

In [36]:
arr_2d[2,:] # 第三行

array([35, 40, 45])

In [37]:
arr_2d[1][0] #第二行第一列

20

In [38]:
arr_2d[1,0] #第二行第一列

20

- 这里的表达需要注意一下

In [39]:
#Shape (2,2) 右上角，不包括 第二行，
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [40]:
# 第0行，不包括第一行
arr_2d[:1] 

array([[ 5, 10, 15]])

In [44]:
# 第0列
arr_2d[:,0] 

array([ 5, 20, 35])

In [46]:
arr_2d[:,-1] 

array([15, 30, 45])

In [48]:
arr_2d[::-1] 

array([[35, 40, 45],
       [20, 25, 30],
       [ 5, 10, 15]])

### 四、bool索引

In [49]:
# 在索引操作中，不仅可以用具体位置进行索引，还可使用bool类型
tang_array = np.arange(0, 100, 10) #0~10 间的整数序列 10是步长
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
mask = np.array([0,0,0,1,1,1,0,0,1,1], dtype=bool)
mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [51]:
# 接下来可以通过布尔类型的索引来选择元素：
tang_array[mask] 

array([30, 40, 50, 80, 90])

- 也可以这样

In [52]:
random_array = np.random.rand(10) # 在[0,1)随机选择10个数
random_array

array([0.81018586, 0.60145142, 0.49918939, 0.40640183, 0.81006007,
       0.27605508, 0.15556067, 0.48910672, 0.45366474, 0.38180091])

In [53]:
mask2 = random_array > 0.5
mask2

array([ True,  True, False, False,  True, False, False, False, False,
       False])

In [54]:
random_array[mask2]

array([0.81018586, 0.60145142, 0.81006007])